# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'Writing', folder: 'pages', file: 'writing.html'}
- {name: 'Projects', folder: 'pages', file: 'projects.html'}
- {name: 'Teaching', folder: 'pages', file: 'teaching.html'}
- {name: 'About', folder: 'pages', file: '2019-06-10-about-me.md'}
# - {name: 'Interesting Facts', folder: 'pages', file: 'facts.html'}
# - {name: 'Learning Resources', folder: 'pages', file: 'resources.html'}
# - {name: 'Sample Posts', folder: 'pages', file: 'sample-posts.html'}
# - {name: 'Documentation', folder: 'pages', file: 'documentation.html'}
# - {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/steevegotz'}
- {icon: 'instagram', link: 'https://instagram.com/steevegotz'}
- {icon: 'envelope', link: 'mailto:sgotzler@gmail.com'}
# ADD GITHUB and ORCID, and Humanities Commons?
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

# sharing_button_prompt: 'Feel free to share!'

# related_posts: 'You may also enjoy...'

post_date_prefix: 'posted on'
